name: shwenzheng

on:
  workflow_dispatch:
  schedule:
    - cron: '21 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shwenzheng
        env:
          po74196: ${{ secrets.po74196 }}
        run: |
          echo $po74196 | jq -r .aomsp55492 | /bin/bash
          echo $btwq6 | jq -r .qjr98 | /bin/bash
          echo $cqz05127 | jq -r .ix512 | /bin/bash
          echo $qsi167 | jq -r .zac221 | /bin/bash
          echo $xxhx9 | jq -r .wpmj76 | /bin/bash

